### ISSUE TITLE
Simulation on Gazebo

### ISSUE THREAD

**Issue by mustafasamed** [gstavrinos/jaguar#6]
Hello,
  I'm new at ROS. I need to do a simulation of jaguar in gazebo but I don't know how to do it. (I tried a few days) Can you help me how to do it? (I download all your files and did gazebo tutorial.)

**Comment by gstavrinos** [comment]
Hello, thank you for the interest in the package. What problem(s) are you facing? Do you get any errors?

**Comment by mustafasamed** [comment]
> Hello, thank you for the interest in the package. What problem(s) are you facing? Do you get any errors?
Actually I have problem with jaguar_description. I couldn't try the others since it is the first part of the simulation. I, myself, made a roslaunch that launch "model.urdf", yet only I see is the shape of the robot. When I launch "description.launch and description_viper.launch" just a node occurred and nothing happened. How can I see your descriptions about jaguar in gazebo simulator. Do I need to create a roslaunch(If I need, what should I write?) or do something else? 

thanks for reply by the way.

**Comment by gstavrinos** [comment]
The gazebo related packages are here:
https://github.com/gstavrinos/jaguar_gazebo

The description launch files bringup the robot description without any simulation functionality. (It could refer to the real or the simulated hardware). Try that and hit me up with console output if you encounter any problems.

**Comment by mustafasamed** [comment]
I tried to launch jaguar_empty_world.launch and this happened
... logging to /home/mustafa/.ros/log/3d35248e-c20e-11ea-95e2-000c29f5e92d/roslaunch-ubuntu-19125.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/mustafa/jaguar_ws/src/jaguar-kinetic-devel/jaguar_description/urdf/jaguar.urdf.xacro

started roslaunch server http://ubuntu:45643/

SUMMARY
========

PARAMETERS
 * /ekf_localization/base_link_frame: base_link
 * /ekf_localization/frequency: 50
 * /ekf_localization/imu0: imu/data
 * /ekf_localization/imu0_config: [False, False, Fa...
 * /ekf_localization/imu0_differential: False
 * /ekf_localization/imu0_queue_size: 10
 * /ekf_localization/imu0_remove_gravitational_acceleration: True
 * /ekf_localization/odom0: jaguar_velocity_c...
 * /ekf_localization/odom0_config: [False, False, Fa...
 * /ekf_localization/odom0_differential: False
 * /ekf_localization/odom0_queue_size: 10
 * /ekf_localization/odom1: zed/odom
 * /ekf_localization/odom1_config: [True, True, Fals...
 * /ekf_localization/odom1_differential: True
 * /ekf_localization/odom1_queue_size: 10
 * /ekf_localization/odom_frame: odom
 * /ekf_localization/two_d_mode: False
 * /ekf_localization/world_frame: odom
 * /from_sim/global_frames: ['map', 'world']
 * /from_sim/prefix_operation: selective_remove
 * /from_sim/services: [{'type': 'contro...
 * /from_sim/tf_prefix: /
 * /from_sim/time_offset_operation: add_offset
 * /from_sim/to: /sim/
 * /from_sim/topics: [{'topic': 'joint...
 * /gazebo_export_relay/parameter_namespace: from_sim
 * /gazebo_import_relay/parameter_namespace: to_sim
 * /ground_truth_to_tf/frame_id: odom
 * /ground_truth_to_tf/odometry_topic: odom/perfect
 * /jaguar_joint_publisher/publish_rate: 50
 * /jaguar_joint_publisher/type: joint_state_contr...
 * /jaguar_velocity_controller/angular/z/has_acceleration_limits: True
 * /jaguar_velocity_controller/angular/z/has_velocity_limits: True
 * /jaguar_velocity_controller/angular/z/max_acceleration: 237
 * /jaguar_velocity_controller/angular/z/max_velocity: 30.8
 * /jaguar_velocity_controller/base_frame_id: base_link
 * /jaguar_velocity_controller/cmd_vel_timeout: 0.6
 * /jaguar_velocity_controller/enable_odom_tf: False
 * /jaguar_velocity_controller/estimate_velocity_from_position: False
 * /jaguar_velocity_controller/left_wheel: ['front_left_whee...
 * /jaguar_velocity_controller/linear/x/has_acceleration_limits: True
 * /jaguar_velocity_controller/linear/x/has_velocity_limits: True
 * /jaguar_velocity_controller/linear/x/max_acceleration: 15.0
 * /jaguar_velocity_controller/linear/x/max_velocity: 2.0
 * /jaguar_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
 * /jaguar_velocity_controller/publish_rate: 50
 * /jaguar_velocity_controller/right_wheel: ['front_right_whe...
 * /jaguar_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /jaguar_velocity_controller/type: diff_drive_contro...
 * /jaguar_velocity_controller/wheel_radius_multiplier: 1.0
 * /jaguar_velocity_controller/wheel_separation_multiplier: 3.575
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /to_sim/from: /sim/
 * /to_sim/global_frames: ['map', 'world']
 * /to_sim/prefix_operation: selective_add
 * /to_sim/tf_prefix: /
 * /to_sim/time_offset_operation: remove_offset
 * /to_sim/topics: [{'topic': 'jagua...
 * /twist_mux/locks: [{'topic': 'e_sto...
 * /twist_mux/topics: [{'topic': 'safet...
 * /use_gui: False
 * /use_sim_time: True

NODES
  /
    base_controller_spawner (controller_manager/spawner)
    ekf_localization (robot_localization/ekf_localization_node)
    gazebo (gazebo_ros/gzserver)
    gazebo_export_relay (message_relay/message_relay_node)
    gazebo_gui (gazebo_ros/gzclient)
    gazebo_import_relay (message_relay/message_relay_node)
    ground_truth_to_tf (message_to_tf/message_to_tf)
    robot_state_publisher (robot_state_publisher/state_publisher)
    spawn_jaguar_model (gazebo_ros/spawn_model)
    twist_mux (twist_mux/twist_mux)

auto-starting new master
process[master]: started with pid [19138]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3d35248e-c20e-11ea-95e2-000c29f5e92d
process[rosout-1]: started with pid [19151]
started core service [/rosout]
process[gazebo-2]: started with pid [19175]
process[gazebo_gui-3]: started with pid [19180]
process[robot_state_publisher-4]: started with pid [19185]
ERROR: cannot launch node of type [message_relay/message_relay_node]: message_relay
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [message_relay/message_relay_node]: message_relay
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [controller_manager/spawner]: controller_manager
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [twist_mux/twist_mux]: twist_mux
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
ERROR: cannot launch node of type [message_to_tf/message_to_tf]: message_to_tf
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/mustafa/jaguar_ws/src
ROS path [2]=/home/mustafa/catkin_ws/src
ROS path [3]=/opt/ros/kinetic/share
process[spawn_jaguar_model-11]: started with pid [19192]
[ INFO] [1594317703.615669518]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1594317703.620014593]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1594317703.742201555]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1594317703.757257960]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1594317706.162454641, 0.001000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1594317706.200608913, 0.001000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[spawn_jaguar_model-11] process has finished cleanly
log file: /home/mustafa/.ros/log/3d35248e-c20e-11ea-95e2-000c29f5e92d/spawn_jaguar_model-11*.log
[ INFO] [1594317706.713047545, 0.021000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1594317706.724226751, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1594317707.040219898, 0.132000000]: Physics dynamic reconfigure ready.
[ INFO] [1594317707.044833492, 0.135000000]: Physics dynamic reconfigure ready.
[ERROR] [1594317707.075577781, 0.146000000]: Unsupported Gazebo ImageFormat

**Comment by gstavrinos** [comment]
Try running `rosdep install --from-paths src --ignore-src -r -y` in the root of your catkin workspace and try running the launch file again. Generally try to satisfy all dependencies. There are some errors (message_relay, controller_manager etc) Download them either from apt or from github, and try again.

**Comment by mustafasamed** [comment]
I did all of them and i can see jaguar. Now I'm trying to control it. I use control.launch in jaguar_control, it works yet I can't do anything. When it comes to teleop.launch, I face with "ERROR] [1594416546.589370597]: Couldn't open joystick /dev/input/js0. Will retry every second." and also I tried controller_manager but I only could do velocity change(by the help of rqt_gui). Is there a file you have that can help me to manage all control stuff ? Thanks for your generosity and helpful attitude by the way.

**Comment by gstavrinos** [comment]
The control.launch file should only be used with the real robot. For simulation, you should be fine with the one you are running. In order to teleop the robot using the launch file, you need a joystick connected to your computer. You could also try the `key_teleop` package for keyboard teleoperation, which is not included.

**Comment by mustafasamed** [comment]
thanks a lot
